### PR TITLE
Fix #505 - Add support for media type 'Collection' in SearchMultiAsync

### LINKED ISSUE #505: SearchMultiAsync() throws exception when media type of result is collection
When we use the SearchMultiAsync() and one of the result's `media_type` is collection. then a `System.NullReferenceException` is experienced.

To reproduce call the SearchMultiAsync with query = `"Star Wars Collection"` : `SearchMultiAsync("Star Wars Collection").

To check actual response from TMDB
```bash
curl --request GET \
     --url 'https://api.themoviedb.org/3/search/multi?query=Star%20Wars%20Collection&include_adult=false&language=en-US&page=1' \
     --header 'Authorization: Bearer <token here>' \
     --header 'accept: application/json'
```

---
I have investigated some code and found that the error is thrown at https://github.com/jellyfin/TMDbLib/blob/7a6477ff48b000d2b7f488a8db964e9ddb8497b4/TMDbLib/Utilities/Converters/SearchBaseConverter.cs#L29

because the https://github.com/jellyfin/TMDbLib/blob/7a6477ff48b000d2b7f488a8db964e9ddb8497b4/TMDbLib/Objects/General/MediaType.cs class does not have a value for type "collection".

### PR DESCRIPTION
**Pull request by DineshSolanki**
This commit introduces the new media type 'Collection' to the MediaType enum and updates the relevant converters and data models to handle it. The SearchCollection class is enhanced to manage additional data and dynamically retrieve 'title' and 'original_title' fields from JSON if they are not directly set. This ensures better data consistency and expands the functionality to include collections as the returned result from searchMulti for collection has no name or original name property.

### CODE REVIEW

File: TMDbLib/Objects/Search/SearchCollection.cs [hunk 1]
```diff
@@ -1,26 +1,59 @@
...
         public bool Adult { get; set; }
         
         [JsonProperty("backdrop_path")]
         public string BackdropPath { get; set; }
-
-        [JsonProperty("id")]
-        public int Id { get; set; }
+        
+        private string _name;
+        private string _originalName;
```
Comment (Shadowghost) [inline TMDbLib/Objects/Search/SearchCollection.cs:20]:
```suggestion

        private string _name;
        private string _originalName;
```

Why was the `id` field removed?

Comment (DineshSolanki) [reply TMDbLib/Objects/Search/SearchCollection.cs:20]: It's inherited from SearchBase

**Comment by DineshSolanki** [comment]
Hi, can this PR be reviewed again.

File: TMDbLib/Objects/Search/SearchCollection.cs [hunk 2]
```diff
@@ -1,26 +1,59 @@
...
+        
         [JsonProperty("adult")]
         public bool Adult { get; set; }
         
         [JsonProperty("backdrop_path")]
         public string BackdropPath { get; set; }
-
-        [JsonProperty("id")]
-        public int Id { get; set; }
+
```
Comment (Shadowghost) [inline TMDbLib/Objects/Search/SearchCollection.cs:18]:
```suggestion

```

**Review by Shadowghost — APPROVED** [review]

**Review by crobibero — APPROVED** [review]
